# Generated by Django 2.2.19 on 2022-08-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_create',
        ),
    ]
