# Generated by Django 2.2.16 on 2022-08-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления комментария')),
                ('comments_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('comments_post', models.ForeignKey(help_text='Комментарий', on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Комментарий')),
            ],
        ),
    ]
