# Generated by Django 2.2.16 on 2022-09-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments_text',
            new_name='text',
        ),
    ]
